### ISSUE TITLE
New directory not created when non-existent directory specified in the command line

### ISSUE THREAD

**Issue by travis23** [rosenbrockc/live-serial#12]
The ideal behavior would be for a new directory to be created when the user specifies the data be logged to a directory that does not exist. 

The following command
`python liveserial\livemon.py COM4 COM5 COM6 -config capscalescale.cfg -refresh 10 -logdir C:\Users\TNiederhauser\Documents\logs\ThreeSensors -method last`

Gives this error
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\TNiederhauser\\Documents\\logs\\ThreeSensors\\2246023103488.csv'`

**Comment by rosenbrockc** [comment]
Available in Revision 0.1.2.
