### ISSUE TITLE
"Live feed has no sensor data keys. Can't set up plotting."

### ISSUE THREAD

**Issue by travis23** [rosenbrockc/live-serial#15]
Tried to run but got the error "Value Error: Live feed has no sensor data keys. Can't set up plotting." I don't know what "sensor data keys" are.

` [sensor.prox]
dtype=float
port=COM4
label=Proximity
value_index=0

[port.COM4]
port_baud=115200
port_timeout=0.025 `

This may be a different issue...
When I specify "port_encoding=ASCII" it appears to be ignored with the following output. 

`Using script args from config C:\Users\user\Documents\live-serial\prox.cfg.
COM4: using {'port_parity': 'N', 'port_timeout': '0.025', 'port_stopbits': 1, 'encoding': 'UTF-8', 'virtual': False, 'delimiter': '\\s', 'port_baud': '9600'} as config-set serial parameters.`

**Comment by travis23** [comment]
With 115200 baud I needed to set both port_timout and buffertime larger. I also set wait to 10 sec. I think this is resolved. I'll post the other problem as a separate issue.

**Comment by rosenbrockc** [comment]
Changing the wait time is the correct thing to do in this case. I'll update the error message to suggest playing with `wait` parameter value.
