### ISSUE TITLE
port_encoding inconsistent

### ISSUE THREAD

**Issue by travis23** [rosenbrockc/live-serial#17]
When I specify "port_encoding=ASCII" it appears to be ignored with the following output.

Using script args from config C:\Users\user\Documents\live-serial\prox.cfg. COM4: using {'port_parity': 'N', 'port_timeout': '0.025', 'port_stopbits': 1, 'encoding': 'UTF-8', 'virtual': False, 'delimiter': '\\s', 'port_baud': '9600'} as config-set serial parameters.

**Comment by rosenbrockc** [comment]
It turns out that I decided to call it `encoding` instead of `port_encoding`. Just change the option name under that port section.
