### ISSUE TITLE
Logging not working correctly

### ISSUE THREAD

**Issue by travis23** [rosenbrockc/live-serial#18]
The serial port is putting out 2 values separated by a space. The configuration file is shown below. 

```
[sensor.prox]
dtype=int, float
port=COM4
label=Proximity
value_index=2

[port.COM4]
port_baud=115200
port_timeout=0.3
port_encoding=ASCII
# port_delimeter=\s

[global]
wait=10
buffertime=5
logdir=path
```

The beginning of the log file is as follows. It shows the computer system time stamp twice and omits the first value in the serial data, which happens to be an integer. 

```
Time,Value 1,Value 2
1.71905112267,1.71905112267,5.08333333333
1.74497765965,1.74497765965,6.72222222222
1.90651988983,1.90651988983,432.0
2.00033950806,2.00033950806,526.0
2.09400129318,2.09400129318,620.0
```

**Comment by rosenbrockc** [comment]
I was able to reproduce this bug. Fix will be available in Revision 0.1.4.
