### ISSUE TITLE
It is important to log unfiltered data

### ISSUE THREAD

**Issue by travis23** [rosenbrockc/live-serial#19]
I don't know if there is an easy way to do this, but in my opinion, the filtering of the data to be logged should be an "opt-in" situation rather than an "opt-out". I frequently worry about loosing information due to filtering;  I almost never worry about having data files that are too big. I think most people will think this way. Also, data is often pre-filtered by the sensor before it is sent to the serial port. There is usually no point in filtering twice.

**Comment by rosenbrockc** [comment]
Changed in Revision 0.1.4. If the user wants to pollute their HDD, they should be able to.
