### ISSUE TITLE
When logdir=path is not in config file code does not run

### ISSUE THREAD

**Issue by travis23** [rosenbrockc/live-serial#23]
When logdir=path is commented out in the config file the follow error is raised and the code does not run. 
```ValueError: Live feed has no sensor data keys. Can't setup plotting. Try fiddling with the `-wait` parameter.```

The config file is shown below. 
```
[sensor.prox]
dtype=int, float
port=COM3
label=Proximity
value_index=2

[port.COM3]
port_baud=115200
port_timeout=0.3
encoding=ASCII
# port_delimeter=\s

[global]
wait=10
buffertime=5
logdir=C:\Users\TNiederhauser\OneDrive - NewVista Property Holdings, LLC\ProxData\test\
```

**Comment by rosenbrockc** [comment]
I fixed a different issue (making the `-wait` parameter be an *explicit* wait time, before which no plotting is done) and it appears to have fixed this issue.
