### ISSUE TITLE
Enhancement: Plot Multiple Columns/Sensors

### ISSUE THREAD

**Issue by travis23** [rosenbrockc/live-serial#5]
It would be nice to be able to specify multiple columns in the `value_index` option of a sensor; this would produce multiple lines on the single subplot. Also, if an "aggregate" sensor (e.g., sum or difference of real sensor values) could be plotted in a subplot, that would also be nice. E.g.,

```ini
[sensor.total]
port=aggregated
label=Total Weight
sensors=sensor.foot,sensor.seat
function=numpy.sum
```

**Comment by rosenbrockc** [comment]
Available in Revision 0.1.3.
